### ISSUE TITLE
List index out of range.

### ISSUE THREAD

**Issue by JaniniRami** [KalleHallden/reddit_automations#1]
I have specified my network IP and m device IP, but whenever I try to net-listen I get this error:
```
Traceback (most recent call last):
  File "net-listen.py", line 15, in <module>
    connected_ip = line.decode('utf-8').split()[3]
IndexError: list index out of range
```
Any idea on what is causing this error?

**Comment by skyrunner360** [comment]
Same problem here.

**Comment by rashodkorala** [comment]
same here

**Comment by tycooperaow** [comment]
same here

**Comment by SupermanJB** [comment]
Did anyone get the resolution for this?

**Comment by JaniniRami** [comment]
Idts

**Comment by SupermanJB** [comment]
Think I found out what the problem is - He is running it on his Mac and not Windows Machine. To be able to make command you need to enable "Shell=true" in the proc statement. I didnt get this working to be honest, but I did get this working when I ran it on my linux VM. 

The code didnt work for me as expected. I added my Router IP as my network IP and Device IP as the IP I was looking for. It kept on only pinging my router and obviously never met the criteria to say who connect. 

Was expecting this to work similarly to arp -a in windows shell. To show all IP that is connected. 

Did anyone get this working?

**Comment by InvisibleImpostor** [comment]
Guys, I think I found where its going wrong. I use Windows.

I replaced the line `connected_ip = line.decode('utf-8').split()[3]` 
with
`connected_ip = line.decode('utf-8')`
I tried printing `connected_ip` and I get the following output in the Python shell - 

Note -  `my_ip` refers to `NETWORK_IP`

`[]`
`['Pinging', 'my_ip', 'with', '32', 'bytes', 'of', 'data:']`
`['Reply', 'from', 'my_ip', 'bytes=32', 'time=22ms', 'TTL=63']`
`['Reply', 'from', 'my_ip', 'bytes=32', 'time=21ms', 'TTL=63']`
`['Reply', 'from', 'my_ip', 'bytes=32', 'time=20ms', 'TTL=63']`
`['Reply', 'from', 'my_ip', 'bytes=32', 'time=22ms', 'TTL=63']`
`[]`
`['Ping', 'statistics', 'for', 'my_ip']`
`['Packets:', 'Sent', '=', '4,', 'Received', '=', '4,', 'Lost', '=', '0', '(0%', 'loss),']`
`['Approximate', 'round', 'trip', 'times', 'in', 'milli-seconds:']`
`['Minimum', '=', '20ms,', 'Maximum', '=', '22ms,', 'Average', '=', '21ms']`

As we can see from the output the first list is empty. Hence the `List Index out of range error`.

I suggest we use `ping -t "your IP_DEVICE here"` to get a continuous stream of pings.

**Comment by JaniniRami07** [comment]
I made something similar to this and got it working, It basically pings your wanted device continuously until the device connects to the internet.

```
import sys
import subprocess
import os
from decouple import config

IP_NETWORK = '192.168.0.1'
IP_DEVICE = '192.168.0.160'

proc = subprocess.Popen(["ping", '-t', IP_DEVICE],stdout=subprocess.PIPE)

while True:
	line = proc.stdout.readline()
	if not line:
		break
	else:
		None

	try:
		connected_ip = line.decode('utf-8').split()[2].replace(':', '')
		if connected_ip == IP_DEVICE:
			print('Device connected!')
			# Do whatever you want when the device connects here...
			break
		else:
			print('Pinging device...')
	except:
		pass
```

**Comment by JaniniRami** [comment]
I made something similar to this, It basically takes the wanted device, and start pinging the device continuously until it connects to the internet.
```
import sys
import subprocess
import os
from decouple import config

IP_DEVICE = '#DEVICE_IP_HERE'

proc = subprocess.Popen(["ping", '-t', IP_DEVICE],stdout=subprocess.PIPE)

while True:
	line = proc.stdout.readline()
	if not line:
		break
	else:
		None

	try:
		connected_ip = line.decode('utf-8').split()[2].replace(':', '')
		if connected_ip == IP_DEVICE:
			print('Device connected!')
			# Do whatever you want when the device connects here...
			break
		else:
			print('Pinging device...')
	except:
		pass
```

**Comment by adriangrosu09** [comment]
hi , i am new to pyhton
i have this error : ImportError: cannot import name 'config' from 'decouple' (G:\py\venv\lib\site-packages\decouple\__init__.py)
edit:
the error :  i have installed decouple and python-decouple from pip , uninstalled decouple 
fixed  now works ! ty

**Comment by unsigned1nt** [comment]
I couldn't get this script to work, though I have found one working for me.

[See original script](https://github.com/davidbombal/red-python-scripts/blob/main/lanscan_arp.py)

I have made a few tweaks to work with the .env and settings.ini files.

## My script
```python
import scapy.all as scapy # Works with 2.4.4, not 2.4.5
import re
from decouple import config

# Regular Expression Pattern to recognise IPv4 addresses.
ip_add_range_pattern = re.compile("^(?:[0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]*$")

# Get the address range to ARP
while True:
    ip_add_range_entered = config("IP_NETWORK") + "/24"
    if ip_add_range_pattern.search(ip_add_range_entered):
        print(f"{ip_add_range_entered} is a valid ip address range")
        break


# Try ARPing the ip address range supplied by the user. 
# The arping() method in scapy creates a pakcet with an ARP message 
# and sends it to the broadcast mac address ff:ff:ff:ff:ff:ff.
# If a valid ip address range was supplied the program will return 
# the list of all results.
arp_result = scapy.arping(ip_add_range_entered)
```

Shout out to @davidbombal for the original

## Important
If you use Windows, like me, you'll need to install WinPcap or Npcap.

## Environment
* Platform: Windows 10
* Python: 3.8.1
* Scapy version: 2.4.4
* WinPcap version: 4.1.3

**Comment by AayushVyasKIIT** [comment]
pinging devices is a uncertain process, some device responds ,some does not responds back. In my case iphone6S responded, realme Narzo20pro did not. 
I made a fresh app with the started idea, but now it can detect anyone connected to your network.
It also gives you a **push notification** describing the event.
![check this](https://github.com/AayushVyasKIIT/intruder_alert/tree/4ad9b33c35eabd426c138136325addbb4c096641)
